// generated by @ver5/vite-plugin-utools
// DO NOT CHANGE THIS FILE!
/// <reference types="@ver5/vite-plugin-utools/utools" />

interface Window {
  preload: {
    execSync: typeof import('./preload')['execSync']
    fs: typeof import('./preload')['fs']
    getIndexHTML: typeof import('./preload')['getIndexHTML']
    getIndexjs: typeof import('./preload')['getIndexjs']
    longExec: typeof import('./preload')['longExec']
    openUrl: typeof import('./preload')['openUrl']
    osascriptExec: typeof import('./preload')['osascriptExec']
    pathJoin: typeof import('./preload')['pathJoin']
    readAsarFile: typeof import('./preload')['readAsarFile']
    run: typeof import('./preload')['run']
    startAsarServer: typeof import('./preload')['startAsarServer']
  }
}