// generated by @ver5/vite-plugin-utools
// DO NOT CHANGE THIS FILE!
/// <reference types="@ver5/vite-plugin-utools/utools" />

interface Window {
  preload: {
    fs: typeof import('./preload')['fs']
    longExec: typeof import('./preload')['longExec']
    run: typeof import('./preload')['run']
  }
}