// generated by @ver5/vite-plugin-utools
// DO NOT CHANGE THIS FILE!
/// <reference types="@ver5/vite-plugin-utools/utools" />

interface Window {
  preload: {
    setName: typeof import('./preload')['setName']
    test: typeof import('./preload')['test']
    xxx: typeof import('./preload')['xxx']
  }
}